format_version: 10
pipelines:
  ci:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-71ec009:
        git: https://git.mita.me/Mitame/CI-test
        shallow_clone: false
        auto_update: false
        branch: main
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                - --verbose
                - --workspace
                command: cargo
                run_if: passed
